# Generated by Django 5.2.7 on 2025-11-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('position', models.ManyToManyField(to='portfolio.position')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
